#!/usr/bin/env bash
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"

#!/usr/bin/env bash
alias esc="$HOME/.config/sway/config"
alias vim="$VIM"
alias work="cd ~/work"
alias personal="cd ~/.config/personal"
alias wifi="nmtui"
alias audio="pavucontrol"
alias waifuv="~/tools/waifu/waifu2x-ncnn-vulkan"
alias android='/opt/android-studio/bin/studio.sh'
alias video="v4l2-ctl --list-devices"
alias fix_video="sudo usermod -a -G video $(whoami)"
alias fix_screen="xrandr --output HDMI-0 --mode 1920x1080"
alias record_screen="ffmpeg -f x11grab -s 2560x1440 -i :1+1920,0"
alias devices="xinput --list"
alias check_port="sudo lsof -i"
alias hfzf='history | awk '\''{$1=""; sub(/^[ \t]+/, ""); print $0}'\'' | fzf --border --ansi | xclip -selection clipboard'
alias sudo='sudo env PATH=$PATH'


# alias pmd="$HOME/pmd-bin-7.0.0-rc4/bin/pmd"

alias python="python3"
alias yolo="git push origin master --force --no-verify"
alias eirc="nvim $XDG_CONFIG_HOME/i3/config"

alias killBT="rfkill block bluetooth"
alias unKillBT="rfkill unblock bluetooth"
alias cclip="xclip -selection clipboard"
alias pclip="xclip -selection clipboard -o"

alias bookmap7.4='~/bookmap/7.4/bookmap_runscript.sh'
alias bookmap7.5='~/bookmap/7.5/bookmap_runscript.sh'
alias bookmap7.6='~/bookmap/7.6/bookmap_runscript.sh'
alias vim='nvim'
alias goland='~/lang/go/bin/goland.sh'

alias bmvpn1='sudo openvpn --config ~/work/vpn/client.ovpn'
alias bmvpn3='sudo openvpn --config ~/work/vpn/rg-fw01-ch4-UDP4-1195-stoder.ovpn'
alias firefox='~/utils/firefox/firefox'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias jira='~/tools/jira_1.4.0_linux_x86_64/bin/jira'

alias tms='tmux-sessionizer'
alias itms='important-sessionizer'
alias docker='sudo docker'

alias gpoc='git pull origin $(git branch --show-current) --rebase'
