#!/usr/bin/env bash
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"

#!/usr/bin/env bash
alias esc="$HOME/.config/sway/config"
alias vim="$VIM"
alias work="cd ~/work"
alias personal="cd ~/.config/personal"
alias wifi="nmtui"

alias python="python3"
alias yolo="git push origin master --force --no-verify"
alias eirc="nvim $XDG_CONFIG_HOME/i3/config"

alias killBT="rfkill block bluetooth"
alias unKillBT="rfkill unblock bluetooth"
alias cclip="xclip -selection clipboard"
alias pclip="xclip -selection clipboard -o"

alias bookmap='~/bookmap/bookmap_runscript.sh'
alias bookmap7.5='~/bookmap7.5/bookmap_runscript.sh'
alias vim='nvim'
alias goland='~/GoLand-2023.2.3/bin/goland.sh'

alias idea='intellij-idea-ultimate'
alias bmvpn='sudo openvpn --config ~/work/vpn/client.ovpn'
alias firefox='~/utils/firefox/firefox'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias jira='~/tools/jira_1.4.0_linux_x86_64/bin/jira'

alias tms='tmux-sessionizer'
alias itms='important-sessionizer'
