#!/usr/bin/env bash

addToPath $HOME/.pyenv/bin
addToPath $HOME/.cargo/bin
addToPath $HOME/lang/go/bin
addToPath $XDG_CONFIG_HOME/scripts
#addToPath $HOME/tools/jira_1.4.0_linux_x86_64/bin
addToPath $JAVA_HOME/bin
addToPath /opt/nvim-linux64/bin
addToPath $HOME/lang/go/bin
addToPath $HOME/lang/julia-1.8.1/bin
addToPath $HOME/.local/bin
addToPath $HOME/.local/share/nvim/mason/bin
addToPath $KOTLIN_HOME/bin


# LSP
addToPath $HOME/.config/lsp/kotlin/bin

# Tools
addToPath $HOME/tools/visualvm/bin
addToPath $HOME/tools/telegram
